require('plugins')
require('base')
require('color')
require('p-lint')
require('maps')
require('text')

require('p-dap')
require('p-gitsigns')
require('p-harpoon')
require('p-lsp')
require('p-lualine')
require('p-refactoring')
require('p-silicon')
require('p-telescope')
require('p-todo')
require('p-tree')
require('p-treesitter')
