require('base')
require('maps')
require('plugins')
require('color')
require('text')

require('p-arduino')
require('p-bufferline')
require('p-dap')
require('p-gitsigns')
require('p-lsp')
require('p-lualine')
require('p-mason')
require('p-silicon')
require('p-telescope')
require('p-todo')
require('p-tree')
require('p-treesitter')
